generator:
    resource: "@GeneratorBundle/Resources/config/routing.yml"
    prefix:   /

niwo:
    resource: "@NiwoBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /
