niwo_integrity:
    resource: "@NiwoBundle/Controller/IntegrityController.php"
    type:     annotation

niwo:
    resource: "@NiwoBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /
