<?php

namespace NiwoBundle\Repository;

/**
 * HousingPropertyRightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingPropertyRightsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOwnerId(string $owner_id)
    {
        $result = $this->findBy(["ownerId" => $owner_id]);

        return count($result) > 0 ? $result : null;
    }

    public function findByOwnerIdHash(string $owner_id_hash)
    {
        $result = $this->findBy(["owner_id_hash" => $owner_id_hash]);

        return count($result) > 0 ? $result : null;
    }
}
