<?php

namespace NiwoBundle\Repository;

/**
 * IntegrityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOwnerId(string $owner_id)
    {
        return $this->findBy(["ownerId" => $owner_id]);
    }
}
