<?php

namespace NiwoBundle\Repository;

/**
 * land_rightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandRightsRepository extends \Doctrine\ORM\EntityRepository
{
}
