<?php

namespace NiwoBundle\Repository;

/**
 * LandBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
