<?php

namespace NiwoBundle\Repository;

/**
 * PartBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartBRepository extends \Doctrine\ORM\EntityRepository
{
}
