<?php

namespace NiwoBundle\Repository;

/**
 * PortraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortraitRepository extends \Doctrine\ORM\EntityRepository
{
}
