<?php

namespace NiwoBundle\Repository;

/**
 * RentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHash(string $hash)
    {
        $res = $this->findBy(["hash" => $hash]);

        return $res[0] ?? null;
    }

    public function findbyPartyaIdNumber(string $id)
    {
        $res = $this->findBy(["partyaId" => $id]);

        return $res;
    }
}
