<?php

namespace NiwoBundle\Repository;

/**
 * WoollandRightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WoollandRightsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOwnerId(string $owner_id)
    {
        $result = $this->findBy(["ownerId" => $owner_id]);

        return count($result) > 0 ? $result : null;
    }
}
